### ISSUE TITLE
Conditional image generation problem

### ISSUE THREAD

**Issue by Ivvvvvvvvvvy** [dome272/VQGAN#6]
Hello, your tutorial is great! I have a question I would like to ask, how do I add conditions in the form of pictures when training the second stage transformer

**Comment by dome272** [comment]
Hey there, first of all I would suggest maybe not using the second stage as described here anymore as there are much better methods now. You can look into papers for MaskGIT (https://arxiv.org/abs/2202.04200), Paella (https://arxiv.org/abs/2211.07292) or MUSE (https://arxiv.org/abs/2301.00704) as they are more efficient. Secondly to answer the question, there are many different ways to add condition. You could condition on CLIP image embeddings through ModulatedLayernorms or CrossAttention. Or you could condition on images by concatenating the images to the latents that you are training on. Let me know if that helps

**Comment by Ivvvvvvvvvvy** [comment]
> Hey there, first of all I would suggest maybe not using the second stage as described here anymore as there are much better methods now. You can look into papers for MaskGIT (https://arxiv.org/abs/2202.04200), Paella (https://arxiv.org/abs/2211.07292) or MUSE (https://arxiv.org/abs/2301.00704) as they are more efficient. Secondly to answer the question, there are many different ways to add condition. You could condition on CLIP image embeddings through ModulatedLayernorms or CrossAttention. Or you could condition on images by concatenating the images to the latents that you are training on. Let me know if that helps

Thanks a lot！！！i will try！
